### ISSUE TITLE
Log and metrics tracking for Docker services

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1256]
# User Story
- As a platform engineer I need visibility into the services that I run via logs and metrics

# Description/Context
As we migrate more of our services to run via docker-compose on EC2 instances we need a standardized way of collecting logs and metrics. We use Grafana as the storage/query/visualization layer for those metrics and Vector as the collector. We need a solid default configuration for Vector that collects information that aids us in monitoring, alerting, and debugging.

# Acceptance Criteria
- [ ] Vector collects the logs from the running containers and sends them to Grafana's installation of Loki associated with the running instance (e.g. CI -> CI, etc.)
- [ ] Vector collects metrics for the running containers and sends them to Grafana's installation of Prometheus. One option is to use [cAdvisor](https://github.com/google/cadvisor) for exposing those metrics via a Prometheus endpoint.
- [ ] Vector has a default configuration snippet managed via Vault agent templates or consul-template that manages the credentials for Grafana so that we don't have to pass them through EC2 userdata

# References
Some interesting resources that I came across when looking at cAdvisor for use with Grafana:
- https://github.com/vegasbrianc/grafana_dashboard
- https://github.com/vegasbrianc/docker-traefik-prometheus
- https://github.com/vegasbrianc/prometheus

**Comment by Ardiea** [comment]
Partially addressed here:
https://github.com/mitodl/ol-infrastructure/pull/1281
https://github.com/mitodl/ol-infrastructure/pull/1280

**Comment by blarghmatey** [comment]
@Ardiea can you weigh on on the status of this and whether we can consider it complete? If it's not complete, should we create a new issue to capture any remaining work, or just keep this one open?

**Comment by Ardiea** [comment]
Log collection is greatly improved. There are no metric collections to speak of and I've not even considered it. So I can close this and open a new one for investigating that. I think there is cadvisor or something?
