### ISSUE TITLE
Schedule user edX user retirement pipeline using Tubular image

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1309]
# User Story
As a product owner for MITx Online and other edX backed applications I want a way to be able to properly retire user accounts from Open edX

# Description/Context
In order to be able to comply with GDPR we need to be able to properly delete or obfuscate user data. edX has a mechanism for this which is implemented as a scheduled task that runs in CI which periodically calls a set of APIs on the Open edX application. We need to build a pipeline which runs that task on a schedule with the proper configuration for retiring users in a given installation.

# Acceptance Criteria
- [ ] A Concourse pipeline is written which executes the sequence of scripts for user retirement on a recurring schedule
- [ ] The pipeline is written in a way that it can be reused across different edX installations

# Additional Resources
https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/user_retire/driver_setup.html

# Tasks
```[tasklist]
- [x] Study [Concourse docs](https://concourse-ci.org/docs.html) and Tobias's awesome Python data model generated [resource wrappers](https://github.com/mitodl/ol-infrastructure/tree/cpatti_openedx_tubular/src/concourse/lib).
- [x] Figure out how to properly configure tubular - it requires a million environment variables. Where do those come from?
- [x] Adapt the installation and configuration doc into the [Concourse pipeline Python script](https://github.com/mitodl/ol-infrastructure/blob/cpatti_openedx_tubular/src/concourse/pipelines/open_edx/tubular/tubular.py)
- [x] Create pipeline in CI
- [x] Validate and tweak configuration accordingly
```

**Comment by pdpinch** [comment]
Doing this should be part of solving https://github.com/mitodl/mitxonline/issues/697

**Comment by feoh** [comment]
Ungh SOOO close! :)

The [pipeline](https://cicd.odl.mit.edu/teams/mitxonline/pipelines/misc-cloud-tubular) is up and running but failing because somehow the configuration I'm pulling in with Git isn't appearing where I need it in the container.

**Comment by feoh** [comment]
* End to end pipeline run successful in QA!
* [Draft pull request](https://github.com/mitodl/ol-infrastructure/pull/1523) submitted.

**Comment by feoh** [comment]
Pipelines:
* [QA](https://cicd-qa.odl.mit.edu/teams/mitxonline/pipelines/misc-cloud-tubular)
* [Production](https://cicd.odl.mit.edu/teams/mitxonline/pipelines/misc-cloud-tubular)

PR merged. Will file related isse to get tubular environment variable configuration fixes upstreamed.

**Comment by feoh** [comment]
I was being a bit premature and naive closing this issue :)

The pipeline itself is working like a champ.

The problem is that when we tried to retire a batch of users today, the OpenEdX retirement API claims those username/email combinations weren't valid even though we can bring the users up in the admin web UI.

So, the further tasks are as follows:

- [ ] Figure out a way to trigger retirement despite the fact that retire_user is refusing to do so. Ben from OpenEdX may be able to help
- [ ] Research the opencraft retire user Django app mentioned [in this article](https://opencraft.com/demystifying-user-retirement-in-the-open-edx-platform/) it may both ease the workflow burden going forward and get us past this problem.
