### ISSUE TITLE
Epic: AWS managed service monitoring

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#1323]
# User Story
As a devops engineer, I want to know when one of our aws managed services is reaching capacity. Things like RDS and Elasticache. We should implement monitoring and alerting of these resources as part of provisioning with pulumi. That means creating the pulumi infrastructure code to create metricAlerts that go with managed service instances and ensuring that those alerts are routed appropriately (don't wake someone up for a CI elasticache CPU being pegged ... but definitely wake someone up for Production.) 

- [x] Create parent cloudwatch alarm component resource  :  In Progress
- [x] Create a component resource for cloudwatch alarms - RDS  :  In Progress
- [x] Create a component resource for cloudwatch alarms - elasticache   :  In Progress
- [x] Create concrete alarms - RDS
- [x] Create concrete alarms - Elasticache
- [x] Test alarms - RDS
- [x] Test alarms - Elasticache 
- [X] Create alerting framework in SNS + OpsGenie 
- [X] Evaluate options with grafana + cloudwatch -> alerting 👎
