### ISSUE TITLE
Provide Keycloak as a platform service

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1329]
# User Story
As a platform engineer I need to provide a maintained and supported service to facilitate SSO and integration with external identity services.

# Description/Context
We want to deploy Keycloak and integrate it into our platform services and applications.

```[tasklist]
# Stages
- [x] #1330
- [x] #1331
- [ ] #1332
- [ ] https://github.com/mitodl/ol-infrastructure/issues/1473
- [x] Use Keycloak to secure Dagster
- [x] Use Keycloak to secure Airbyte
```
