### ISSUE TITLE
Increase visibility of pipelines with stalled changes (MVP)

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1557]
# User Story
- As a platform engineer I want to be notified when there are changes in a pipeline that are waiting to be deployed so that I can ensure all updates are released in a timely fashion

# Description/Context
We have numerous pipelines, infrastructure related ones in particular, that have multiple stages corresponding to environment tiers. As a general rule we automatically deploy to the lowest stage (CI or QA) and manually propagate changes to subsequent environments. This is due to the lack of widespread testing that gives us sufficient confidence to trigger those deploys automatically. As a result we are subject to new changes (e.g. new releases of Consul, code changes in edX Forum, etc.) that will sit until someone thinks to manually check on the status of a given pipeline. As the number of pipelines grows this becomes increasingly unwieldy.

At a minimum it would be helpful to have a reusable component for sending notifications (Slack, email, opsgenie, messenger pigeon, ... :shrug: ) when something is waiting to be deployed to a subsequent pipeline stage. What would be even better is if there was a way to use these signals to populate a Heads Up Display of things that are in a waiting state (not sure exactly how that would manifest, but it would certainly be nice).

# Acceptance Criteria

- [ ] Deploys that are waiting to be propagated to higher environments are easily visible and aren't left waiting for someone to manually check on them
- [ ] Mechanism should also represent an easy to access audit log for deployments - "Jane deployed mitx-skynet to production on 3/2/2031 at 05:00 GMT"

# Plan/Design
I think the most natural way to do this given the Concourse primitives is to create a resource definition that can be placed in between environment tasks that watches for changes and raises a notification. It could then monitor a certain channel to be signalled when to push to the next task. One possibility would be to build or integrate with a Slack bot (e.g. [OpsDroid](https://opsdroid.dev/))

There is a large surface area of possible solutions and I'm happy to help explore the possibilities to narrow down on a workable solution.
```[tasklist]
### Tasks
- [x] Evaluate https://github.com/mitodl/concourse-github-issue-resource for suitability to task. How can we use it to accomplish the AC in this bug? How easy will it be to extend going forward?
- [x] Build Python replacement for https://github.com/mitodl/concourse-github-issue-resource using PyConcourse and PyGithub
- [x] Build pipeline for https://github.com/mitodl/concourse-github-issue-resource to create a docker container concourse can consume
- [x] Create a test pipeline to use the new resource
- [ ] Modify the resource so it can take an issue filter rather than requiring discrete issues to be specified in the source: parameter
```

**Comment by feoh** [comment]
Can I ask the obvious question: Have we thought about what it would take to *get* confident in automated continuous delivery? We're not the first people with this problem and I know a number of potential solutions exist. I presume there are specifics about our situation that make these unsuitable but it never hurts to ask.

**Comment by blarghmatey** [comment]
That is definitely the preferred option, but has a much longer road to travel, and is not necessarily the 100% correct solution everywhere. The hope is that this is a shorter path and more broadly applicable, which then gives us runway to make the longer journey through Murkwood to battle the mighty Smaug.

**Comment by feoh** [comment]
OK I like that. Thinking about it I can see where the increased visibility would be helpful even in a 100% CD environment.

**Comment by feoh** [comment]
What about something like [Graphite](https://graphiteapp.org/).  It's basically just a click counter for collecting clicks.

So, we could instrument Concourse such that for every successful stage, it increments the:

infrastructure.docker_pulumi_packer.Production.#NNNN <- build number

- Grafana consumes Graphite metrics, and we could probably trivially create dashboards from them as well.
- Graphite is VERY low overhead - ~1 UDP packet per metric creation
- Easily consumed/integrated by other potential solutions as we move forward

Hosted Graphite is pretty cheap if we're not running it already. Or is there an existing tool we use that would fill this same niche?

**Comment by blarghmatey** [comment]
Some prior art that we _may_ be able to use as-is, but can at least serve as inspiration:
- https://github.com/meshcloud/gate-resource
- https://github.com/concourse/pool-resource

Another thought I had recently was to use GitHub issues that are generated via a Concourse resource as a means of managing the flow. For example, create an issue of "Validate and propagate version 1.14.0 of Vault from CI -> QA" when there's a new version released. Once the issue is closed, it triggers the next stage of the pipeline, etc. This would require custom code, but fits nicely with the rest of our workflow.

**Comment by blarghmatey** [comment]
@feoh there is now a GitHub Issue resource that was developed to help address the goals of this issue. The code is located at https://github.com/mitodl/concourse-github-issue-resource

**Comment by feoh** [comment]
I have sincere concerns about bringing this Rust module on board.

He's consuming a third party Github API module, octocrab, which is fine, but it looks to *me* like he's deserializing and parsing the Concourse API JSON by hand.

If the Concourse API changes over time, we'll need to maintain this bespoke API interface to go along with it.

Taking a quick look on Pypi I see [ConcourseTools](https://github.com/gchq/ConcourseTools/) a ready made Python class that facilitates the creation of custom Concourse issues.

That combined with [PyGitHub](https://github.com/PyGithub/PyGithub) the official Github Python API will make for an easily extensible we can move forward with.

That's my plan as of now. Happy to be convinced otherwise.

**Comment by feoh** [comment]
Wrote the start of a PyConcourse resource class. Open questions:
- How will I pass in the Github auth token?
  - Can I snag that from Vault? Best way to pass it?
  - System Environment maybe?
- Do I want an In or an Out? I get confused as to which is which in the Concourse context. I THINK I want in because this will be a get step like Github.

**Comment by feoh** [comment]
[test pipeline for github issues resource](https://cicd.odl.mit.edu/teams/infrastructure/pipelines/test-github-issues-integ) - currently not working

**Comment by feoh** [comment]
Check step is working perfectly, thanks to @blarghmatey's help!

out step for creation of issues on task success still has problems. Will work through those tomorrow.

**Comment by feoh** [comment]
Tobias helped me get across the finish line with this a couple days ago.

Today I finished up the initial documentation and so I think we're good for the MVP.

I created #1858 to handle next steps and actual first implementation.
