### ISSUE TITLE
Implement monitoring and alerting for Celery queues

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#1609]
# User Story

- As a platform owner I want to know whether Celery task queues are operating properly
- As a developer I want to be able to easily debug the status and progress of my Celery tasks

# Description/Context

A majority of our applications have Celery as a core component of their functionality. We need a maintainable and easily replicated method for gaining visibility into our Celery queues, including alerting when they are not processing tasks in a timely fashion.

# Acceptance Criteria

- [x] We have a method for monitoring the status and progress of Celery tasks
- [ ] We have a set of alerts defined to notify us when Celery is not processing tasks

# Plan/Design

- [x] Deploy an instance of https://github.com/kodless/leek for monitoring across all of our Celery brokers
- [x] Integrate https://github.com/danihodovic/celery-exporter into our various Celery applications to get more detailed metrics about performance
  - [x] Generate a default set of Grafana dashboards around the captured celery metrics to simplify evaluation of problems
```[tasklist]
### Tasks
- [x] Add Keycloak forward auth via Traefik
- [ ] Make sure that all the celery configs that Leek highlights are applied to all the cemery workers for all OpenEdX projects.
- [ ] Configure Leek's alert triggering capabilities
```

**Comment by feoh** [comment]
Building opensearch cluster. Stumbled over which consul to use. Figured that out, now need to figure out how to wire in the VPC as the stack build is failing on that.

**Comment by feoh** [comment]
Got the [pipeline](https://cicd.odl.mit.edu/teams/infrastructure/pipelines/packer-pulumi-celery-monitoring) built and working up to the point where it hits the Pulumi build, which breaks because it's incomplete.

Struggling to wrap my brain around the mechanics of how we feed redis broker info in from the other Pulumi builds.

**Comment by feoh** [comment]
Successfully wrote the code to pull redis broker info and secret token in from the other stacks and write them to a Vault kv2 secret.

Next I need to create an celery monitoring output from the Vault stack and wire the bilder project up to consume the broker data from Vault -> consul template.

Then there's some more VPC work to do and I will almost certainly need to review and tweak the Traefik configuration to suit task.

**Comment by feoh** [comment]
Details around the VPC work:
- Need to grant the edxapps permissions for their redis cluster to reach out to the leek instance

**Comment by feoh** [comment]
packer pulumi pipeline, AMI build, and misc pulumi infra are all building clean now. Yay :)

Now to figure out how to configure this thing.

**Comment by feoh** [comment]
Re-opening because we're not done here, but I think I'd like to re-scope the remaining work and detail it out more completely so I can get my arms around what and how much remains.

**Comment by feoh** [comment]
Remaining work sketch:

1. Go through auth, copy traefik forward auth from Dagster
2. Make sure that all the celery configs that Leek highlights are applied to all the cemery workers for all OpenEdX projects.
3. Configure Leek's alert triggering capabilities

**Comment by feoh** [comment]
Closing this issue

**Comment by feoh** [comment]
Fixed a bunch of configuration issues but QA is still yielding a 404 when I hit the endpoint :(

I thought maybe the es/opensearch endpoint was misconfigured, but I can hit it and get a response with curl. When I replicate the call it's saying it makes in the logs, I do get a REST response back saying the index doesn't yet exist and to create it from the web UI.

🤦 

Hopefully I can get some time with @blarghmatey to look at this tomorrow.

**Comment by feoh** [comment]
Celery monitoring in QA is up!

https://celery-monitoring-qa.odl.mit.edu/

Requires a keycloak login in the platform engineering realm.

**Comment by feoh** [comment]
This is working in production!!! Tobias says no need to add alerting for now. We're good here! Closing.
