### ISSUE TITLE
create S3 buckets for OCW end to end testing pipeline

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ol-infrastructure#1945]
# Description/Context
With https://github.com/mitodl/ocw-studio/pull/2018, we will add a new end to end testing pipeline definition to `ocw-studio`. This pipeline will build 2 test courses, one `ocw-www` site (aka the root website) and one course site. These sites will then be deployed to S3 and have Playwright run against them. This allows us to run our end to end tests against sites built using the exact same steps as sites published through the UI. 

# Plan/Design
In order for this to work, we will need a total of 4 new S3 buckets. Two of these (the online versions) will need Fastly distributions pointed at them. Ideally, it would look something like this:

 - `ocw-content-test-qa` -> `https://test-qa.ocw.mit.edu/`
 - `ocw-content-offline-test-qa` (no Fastly)
 - `ocw-content-test-production` -> `https://test.ocw.mit.edu/`
 - `ocw-content-offline-test-production` (no Fastly)

The offline buckets would be created pre-emptively, as we currently don't have Playwright tests set up for the offline site. The testing process for the offline site would also be slightly different as it would likely not be tested through a web server, hence why we won't link a Fastly distribution to those buckets. The two online test buckets and Fastly distributions would be in use right away though. If we'd rather wait to create the offline buckets that's fine. If anyone has better suggestions for the bucket names / subdomains feel free to make them as well.
```[tasklist]
### Tasks
- [ ] Update ocw-site Pulumi code to use the new aws.BucketV2 since the old syntax now no longer works
- [ ] Add new S3 buckets as detailed in above design
- [ ] Add Fastly distributions for new buckets
- [ ] Test/validate in CI
- [ ] Roll out QA -> Production
```

**Comment by gumaerc** [comment]
@feoh Those look good, thanks!

**Comment by feoh** [comment]
Hi. I rewrote the Pulumi code for all the S3 buckets, adding the new ones and converting the old ones to the new Terraform BucketV2 API, and I'm seeing an error I don't understand around the draft backup bucket ARN:

```
# cpatti @ rocinante in ~/src/mit/ol-infrastructure/src/ol_infrastructure/applications/ocw_site on git:cpatti_ocw_test_pipeline x ol-infrastructure-yqmQEgvq-py3.11 [17:13:55]
$ pulumi up -s applications.ocw_site.CI
Previewing update (applications.ocw_site.CI):
     Type                               Name                                                             Plan       Info
     pulumi:pulumi:Stack                ol-infrastructure-ocw-site-application-applications.ocw_site.CI             2 warnings
 +   ├─ pulumi:providers:fastly         fastly-provider                                                  create
 ~   ├─ aws:iam:Policy                  ocw-site-ci-policy                                               update     [diff: ~policy]
 +   ├─ aws:s3:BucketV2                 ocw-content-offline-draft-ci                                     create
 +   ├─ aws:s3:BucketV2                 ocw-content-offline-live-ci                                      create
 +   ├─ fastly:index:ServiceVcl         ocw-draft-ci                                                     create
 +   ├─ aws:s3:BucketOwnershipControls  ol-draft-bucket-ownership-controls                               create
 +   ├─ fastly:index:ServiceVcl         ocw-live-ci                                                      create
 +   ├─ aws:s3:BucketVersioningV2       ol-draft-bucket-versioning                                       create
 +   ├─ aws:s3:BucketPublicAccessBlock  ol-draft-bucket-public-access                                    create
 +   ├─ aws:s3:BucketOwnershipControls  ol-live-bucket-ownership-controls                                create
 +   ├─ aws:s3:BucketVersioningV2       ol-live-bucket-versioning                                        create
 +   ├─ aws:s3:BucketPublicAccessBlock  ol-live-bucket-public-access                                     create
 +   ├─ aws:s3:BucketOwnershipControls  ol-draft_backup-bucket-ownership-controls                        create     1 error
 +   ├─ aws:s3:BucketVersioningV2       ol-draft_backup-bucket-versioning                                create
 +   ├─ aws:s3:BucketPublicAccessBlock  ol-draft_backup-bucket-public-access                             create
 +   ├─ aws:s3:BucketOwnershipControls  ol-live_backup-bucket-ownership-controls                         create
 +   └─ aws:s3:BucketVersioningV2       ol-live_backup-bucket-versioning                                 create

Diagnostics:
  aws:s3:BucketOwnershipControls (ol-draft_backup-bucket-ownership-controls):
    error: Duplicate resource URN 'urn:pulumi:applications.ocw_site.CI::ol-infrastructure-ocw-site-application::aws:s3/bucketOwnershipControls:BucketOwnershipControls::ol-draft_backup-bucket-ownership-controls'; try giving it a unique name

```

@gumaerc I appreciate your patience on this and I know you checked in on its status yesterday. This is where I'm at with the task today as of COB.

Please feel free to reach out to @blarghmatey if you feel like this needs to be actioned more urgently than Tuesday, I might even be able to start Monday but there's also the XPro release and associated Heroku -> RDS database cut-over which either won't take long or could take the day.

**Comment by gumaerc** [comment]
@feoh Take your time. That's odd that you'd see a duplicate URN on the ownership controls specifically. I'm not sure why that would be happening, but for what it's worth that backup pipeline lives here: https://cicd-qa.odl.mit.edu/teams/ocw/pipelines/backup-ocw-content/

**Comment by feoh** [comment]
Copy pasta error, that's fixed now :) Just need to get the fastly stuff sorted and we'll be good. Thanks for your patience!

**Comment by feoh** [comment]
I think I have the code in place and have built it in QA. @gumaerc please take a look when you can and see if it's right and I'll build it in production.

Thanks!

**Comment by feoh** [comment]
QA is running with the (very!) updated PR now and @gumaerc says it looks good on first glance.
