### ISSUE TITLE
MITx Online deployment

### ISSUE THREAD

**Issue by shaidar** [mitodl/ol-infrastructure#240]
The initial production deadline for the MITx Online project is September 1st. On that date we will have all services deployed and available for users to start onboarding. By September 15th we anticipate having the majority of initial users onboarded and using the platform regularly. By that time we will have implemented additional scalability and ease-of-deployment fixes for ongoing support of the platform. Following the September 15th date we will continue to iterate on features and capabilities for the platform 
to support users and platform maintainers.

### edx-platform
- [x] Build AMI with Ansible to deploy edx-platform code
- [x] Install Vault/consul-template agent to keep secrets and configuration up to date
- [x] Create auto-scaling group and load balancer  ( July 12th )
- [x] Obtain wildcard certificate for *.mitxonline.mit.edu
- [x] Install edx-sysadmin plugin to edxapp
- [x] Decide on domain name and configure Route53 entries ( July 9th)
  - [x] Create zone in Route 53
  - [x] Request delegation from IS&T
- [x] Template edxapp configuration for use with consul-template
- [x] Setup AWS SES for email
- [x] Install Vector for log collection
- [x] Make edxapp config composable for multiple environments
- [x] edX platform is deployed to production environment (Aug. 18th)
  - [x] Deploy Consul cluster
  - [x] Deploy MongoDB
  - [x] Deploy Elasticsearch
  - [x] Deploy edxapp Pulumi stack
- [x] Fastly set up and configured to work with edx-platform (Aug. 20th)
  - [x] QA
  - [x] Production
- [x] Fastly set up and configured to work with micro-frontend applications (Aug. 20th)
  - [x] QA
  - [x] Production
- [x] MITx Online application integrated with edx-platform (Aug. 19th)
  - [x] QA
  - [x] Production
- [x] Custom theme developed and applied to edx-platform
  - [x] QA
  - [x] Production
- [x] Custom theme developed and applied to micro-frontend applications
  - [x] QA
  - [x] Production
- [x] Tracking logs automatically uploaded to S3
- [x] Micromasters integrated with edx-platform and MITx Online application
  - [x] QA
  - [x] Production
- [x] Waffle flags applied to edx-platform for enabling custom functionality
  - [x] Video image uploads
    - [x] QA
    - [x] Production
  - [x] Bulk mailing
    - [x] QA
    - [x] Production
- [x] Tune load balancer and autoscale group for edxapp to give more warmup time before adding new instances to traffic serving pool
- [x] validate CORS configuration for delivering course videos hosted by edx.org
    - [x] QA
    - [x] Production

### Forum
- [x] Deploy as part of edx-platform EC2 instance

### Heroku
- [x] [Setup Heroku pipeline and app](https://github.com/mitodl/salt-ops/issues/1434)
  - [x] QA
  - [x] Production

### MFE (based on list [here](https://docs.google.com/document/d/1IgcSJ2EI9vpuUFsAQCh_Ul81I5qyl3NjMxaf4DaUELY/edit#heading=h.z49mfwtwl0m5))
- [x] Configure Fastly for proxying to S3 buckets
- [x] Deploy [Learner](https://github.com/edx/frontend-app-learning) MFE and integrate with edx-platform
  - [x] QA
  - [x] Production (Aug. 20th)

### edx-platform
- [x] Gracefully reload edxapp on config updates
- [x] Override logging configuration to allow for use of structlog and Sentry handlers
- [x] Google Analytics configured for edx-platform
- [x] Sentry
  - [x] set up for edx-platform
    - [x] QA
    - [x] Production
  - [x] https://github.com/mitodl/mitxonline/issues/97 set up for MITx Online application
    - [x] QA
    - [x] Production
- [x] Pingdom
  - [x] Configured to monitor uptime of edx-platform
    - [x] QA
    - [x] Production
  - [x] Configured to monitor uptime of MITx Online application
    - [x] QA
    - [x] Production
- [ ] #420
- [x] Install and configure git auto-export plugin
- [x] Configure SSH private key for git import support from private repositories

### edX Notes
- [ ] Create a docker build for [edx-notes-api](https://github.com/edx/edx-notes-api) ( in progress )
- [ ] Create an ECS Fargate deployment for edx-notes (in progress )

### edx-platform
- [x] Configure Proctortrack integration - October 8th
- [x] Run load tests against LMS to validate ASG configuration
- [x] #419
- [x] Integrate video publishing from OVS to edxapp

### MFE
- [ ] Create Concourse pipeline instances for each MFE deployment (60%)
- [ ] Deploy [Special Exams](https://github.com/edx/frontend-lib-special-exams) (not MVP feature)
- [ ] Deploy [Gradebook](https://github.com/edx/frontend-app-gradebook)

### Forum
- [ ] [Create a docker build for cs_comments_service](https://github.com/mitodl/ol-infrastructure/issues/163)
- [ ] Create an ECS Fargate deployment for forum

### Xqueue
- [x] [Create a docker build for xqueue](https://github.com/mitodl/ol-infrastructure/issues/162)
- [ ] Create an ECS Fargate deployment for xqueue
- [ ] Integrate xqueue with edxapp
