### ISSUE TITLE
MITx Online Milestone - September 1st

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#320]
For September 1st we will have a fully deployed and integrated installation of the Open edX platform and the MITx Online application in a production environment. The set of features that we will be supporting for that date are detailed here:

- [ ] edX platform is deployed to production environment
  - [ ] Deploy Consul cluster
  - [ ] Deploy MongoDB
  - [ ] Deploy Elasticsearch
  - [ ] Deploy edxapp Pulumi stack
- [ ] The learner MFE is deployed and integrated with the edX application
  - [ ] QA
  - [ ] Production
- [ ] Custom theme developed and applied to edx-platform
  - [ ] QA
  - [ ] Production
- [ ] Custom theme developed and applied to micro-frontend applications
  - [ ] QA
  - [ ] Production
- [ ] Fastly set up and configured to work with edx-platform and micro-frontend applications
  - [ ] QA
  - [ ] Production
- [ ] MITx Online app deployed
  - [x] QA
  - [ ] Production
- [ ] MITx Online app integrated with edx-platform
  - [ ] QA
  - [ ] Production
- [ ] Micromasters integrated with edx-platform and MITx Online application
  - [ ] QA
  - [ ] Production
- [ ] Waffle flags applied to edx-platform for enabling custom functionality
  - [ ] Video image uploads
    - [ ] QA
    - [ ] Production
  - [ ] Bulk mailing
    - [ ] QA
    - [ ] Production
- [ ] Pingdom
  - [ ] Configured to monitor uptime of edx-platform
    - [ ] QA
    - [ ] Production
  - [ ] Configured to monitor uptime of MITx Online application
    - [ ] QA
    - [ ] Production
- [ ] validate CORS configuration for delivering course videos hosted by edx.org
    - [ ] QA
    - [ ] Production
- [ ] Sentry
  - [ ] set up for edx-platform
    - [ ] QA
    - [ ] Production
  - [ ] set up for MITx Online application
    - [ ] QA
    - [ ] Production
- [ ] Google Analytics configured for edx-platform
- [x] Tracking logs automatically uploaded to S3
