### ISSUE TITLE
Open edX Maple upgrades 2021

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#448]
As part of our ongoing maintenance of our xPro and residential MITx installations of Open edX we need to upgrade them to the Maple release. During this upgrade cycle we are also migrating off of our SaltStack based deployment structure and onto our Pulumi/Packer/PyInfra approach that we used to launch the MITx Online environment.

To support this migration and bring our environments in line with the rest of our software lifecycle we will also be creating CI environments for the different edX deployments. In addition, we are migrating our MongoDB and Elasticsearch installations to use managed services as a means of simplifying upgrades and lowering maintenance overhead. (Side note that MongoDB is being phased out as part of the edX architecture)

There are multiple steps to make this all work properly:
# CI/Testing
- [x] Create a Pulumi project to manage provisioning of a MongoDB Atlas cluster
- [x] Create a Pulumi project to manage provisioning of an Elasticsearch cluster
- [X] Split Packer build into base and custom layers
  - [X] Install each theme
  - [X] Customize edxapp plugins and versions
- [X] Split Consul templates into separate files for different installations
- [x] Customize templates for each environment
  - [x] Diff the MITx Online template with rendered files on xPro
  - [x] Diff the MITx Online template with rendered files on residential
- [x] Create stack definitions for mitx draft/live and xpro environments (the draft or staging and live deployments for residential will be treated as separate installations, which they effectively are)
- [x] Register MongoDB Atlas service with Consul
- [x] Register Elasticsearch service with Consul
- [x] Create Concourse pipeline for learner MFE on xPro
- [x] Create Concourse pipeline for learner MFE on residential
- [x] Create a Fastly distribution for edxapp on xPro
- [x] Create a Fastly distribution for edxapp on residential
- [x] Deploy xqueue for residential
- [ ] Deploy Blockstore for Residential
- [x] Resolve Elasticsearch access for Forum

# QA
- [x] Deploy OpenSearch Pulumi stack
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Deploy MongoDB Atlas Pulumi stack
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Deploy edxapp Pulumi stack to provision S3 buckets, databases, etc.
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Create Concourse pipeline for learner MFE
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Create a Fastly distribution for edxapp
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Sync existing S3 bucket contents to newly created buckets. Some contents may need to be remapped to different paths within the buckets.
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Import MySQL database contents into newly created instances and schemas
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Import MongoDB contents into MongoDB Atlas installations (using live migration capability)
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Apply edX migrations to MySQL database
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Reindex Forum contents into Elasticsearch
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Configure OAuth login for studio (commands detailed in migration runbook)
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging

# Production
- [x] Notify IS&T of downtime to put on 3Down
  - [x] xPro
  - [x] Residential
- [x] Deploy OpenSearch Pulumi stack
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Deploy MongoDB Atlas Pulumi stack
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Deploy edxapp Pulumi stack to provision S3 buckets, databases, etc.
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Create Concourse pipeline for learner MFE
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Create a Fastly distribution for edxapp
  - [x] xPro (Need to add the ALB host prior to activating distribution)
  - [x] MITx (Need to add the ALB host prior to activating distribution)
  - [x] MITx Staging (Need to add the ALB host prior to activating distribution)
- [x] Sync existing S3 bucket contents to newly created buckets. Some contents may need to be remapped to different paths within the buckets.
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Import MySQL database contents into newly created instances and schemas
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Import MongoDB contents into MongoDB Atlas installations (using live migration capability)
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Apply edX migrations to MySQL database
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Reindex Forum contents into Elasticsearch
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging
- [x] Configure OAuth login for studio (commands detailed in migration runbook)
  - [x] xPro
  - [x] MITx
  - [x] MITx Staging

## Residential
- [x] Update xqwatcher configuration for pointing to xqueue
  - [x] QA
  - [x] Production

### QA
- [x] Stop RabbitMQ cluster
  - [x] xPro
  - [x] MITx
- [x] Stop MongoDB cluster
  - [x] xPro
  - [x] MITx
- [x] Stop Elasticsearch cluster
  - [x] xPro
  - [x] MITx
- [x] Stop old RDS instance
  - [x] xPro
  - [x] MITx
- [x] Destroy RabbitMQ cluster
  - [x] xPro
  - [x] MITx
- [x] Destroy MongoDB cluster
  - [x] xPro
  - [x] MITx
- [x] Destroy Elasticsearch cluster
  - [x] xPro
  - [x] MITx
- [x] Destroy load balancers
  - [x] xPro
  - [x] MITx
- [x] Destroy old RDS instance
  - [x] xPro
  - [x] MITx
- [ ] Delete old S3 buckets
  - [ ] xPro
  - [ ] MITx
  - [ ] MITx Staging
- [x] Destroy old Elasticache clusters
  - [x] xPro
  - [x] MITx
- [x] Delete Cloudfront distributions
  - [x] MITx

### Production
- [x] Stop RabbitMQ cluster
  - [x] xPro
  - [x] MITx
- [x] Stop MongoDB cluster
  - [x] xPro
  - [x] MITx
- [x] Stop Elasticsearch cluster
  - [x] xPro
  - [x] MITx
- [x] Stop old RDS instance
  - [x] xPro
  - [x] MITx
- [x] Destroy RabbitMQ cluster
  - [x] xPro
  - [x] MITx
- [x] Destroy MongoDB cluster
  - [x] xPro
  - [x] MITx
- [x] Destroy load balancers
  - [x] xPro
  - [x] MITx
- [x] Destroy Elasticsearch cluster
  - [x] xPro
  - [x] MITx
- [x] Destroy old RDS instance
  - [x] xPro
  - [x] MITx
- [ ] Delete old S3 buckets
  - [ ] xPro
  - [ ] MITx
  - [ ] MITx Staging
- [x] Delete Cloudfront distributions
  - [x] MITx

- [ ] Update Dagster pipelines to point to updated databases and credential endpoints
  - [ ] xPro
  - [ ] MITx
