### ISSUE TITLE
Monitoring and Alerting Overhaul - Phase 1

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#707]
# General Stuff

- [ ] Hook Grafana + CloudWatch together (Create an IAM role with Pulumi, put keypair in vault. Setup datasource by hand)
- [ ] Write RFC for log labeling and collection
- [ ] Some kind of promotion / source control on dashboard definitions. Look at https://grafana.github.io/grizzly/what-is-grizzly/ 

# Platform Monitoring

- [ ] Disk usage dashboard(s)
- [ ] **Disk usage alerting**
- [ ] CPU utilization dashboard(s)
- [ ] Memory utilization dashboard(s)
- [ ] IO Performance Dashboard(s)

# Application Monitoring and Alerting

- [ ] Collect a starter list of user workflows and the application they go with (Talk to @pdpinch Re: User workflows)
- [ ] Identify failure points to monitor in those workflows.
- [ ] Identify observability elements on those failure points
- [ ] Identify observability shortcomings. What do we need that we are missing and what challenges exist is obtaining the missing information? 

# Capacity Management

- [ ] Dashboard to identify over-provisioned instances and cost saving opportunities (CloudWatch integration may offer something here)

**Comment by blarghmatey** [comment]
@Ardiea can this be closed? It seems like the remaining items can be turned into issues in their own right for more granular tracking.

**Comment by Ardiea** [comment]
Yes. I will close this out and make sure issues for the remaining items get opened up.

**Comment by Ferdi** [comment]
This is a very well written. 

There quite a bit of information and background that get lost when we close these kind of issues.  I wonder how to preserve some of that in our 'discussions' or something like that.

If i have to be picky :

> Write RFC for log labeling and collection

A link to the RFC would been great when you checked the box.

**Comment by blarghmatey** [comment]
Agreed on both points, though it's worth noting that the issue is still available as `closed`. It's not as visible, but we do still have it available for reference if we know to search for it. This is where things like linking to issues in pull requests is valuable to help provide that back-reference.

**Comment by Ardiea** [comment]
RFC Link: https://github.com/mitodl/hq/discussions/6, probably still needs work though.

Closing. Remaining tasks tracked in #822
